version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    ports:
      - "9000:9000"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jacky
      MYSQL_DATABASE: laravel
